### ISSUE TITLE
To-do list for fragment(adding photos)

### ISSUE THREAD

**Issue by ShinYoung-Kim** [ShinYoung-Kim/Weather#2]
- [x] resize photo
- [ ] select 가능한 photo
- [x] fragment와 activity 연결
- [x] button design -> material chip
- [x] material chip effect(related to db)
- [x] 태그 내용 구체화
- [ ] 태그 추가 기능 만들기
- [x] 사진 추가 기능(upload)
- [ ] 사진 추가 기능(take picture)
- [x] db 구현
- [x] fragment 업데이트(날짜, 날씨)
- [x] fragment 수정 -> BottomSheetDialog 적용
- [ ] get real time weather/temp
