### ISSUE TITLE
결정해야할 것 / to-do

### ISSUE THREAD

**Issue by ShinYoung-Kim** [ShinYoung-Kim/Weather#6]
----------결정해야할 것 ------------------
- [ ] 현재 db 구조 괜찮은가?
- [ ] 태그 추가/삭제를 가능하게 할 것인지 -> tag management 기능을 위한 별도의 fragment/activity 필요 -> 만든다면 drawer에 추가하는 것이 좋겠다. -> 단, 굉장히 귀찮 + 복잡
(태그 추가 삭제 만든다면 상상도)
![image](https://user-images.githubusercontent.com/83866983/202914508-39746d2d-418e-414d-858c-4b706ef73991.png)
- [ ] 바로 사진 찍어서 업로드 가능하게 하는 기능 살릴 것인지
- [ ] user image를 넣을까?
- [ ] db를 각 user별로 만들어서 그 안에 각각의 fashion, clothes, statistics 가지도록 만들까?
- [ ] rate를 string으로 int로?
- [ ] 로그인 기능에서 이메일로 인증메일 보내기/이메일 형식이 아니면 warning뜨면서 안 되게 하기 등의 기능 추가
- [ ] statistics에서 cloth, temperature를 child로 담지 말고, temperature 구간별로 child만들고 그 안에 cloth로 child만들고 그 안에 count 담는 건?

----------to-do----------------------------
- [ ] 이미지 업로드와 db 연동
- [ ] db초기화(?) - clothes의 기본값들을 가지고 있어야 함 -> 회원가입할 때 db에 기본적으로 짜둔 clothes 담도록 만들면?
- [ ] statistics에서 wearcount 증가 -> 기존에 해당 cloth, temperature가 존재하는지 확인하고 있다면 증가/없다면 1로 넣는 기능이어서 존재 여부 확인도 힘들고 값 증가시키기도 힘들다... -> 아니면 clothes 초기화 시켜둘 때 statistics도 초기화 시켜둘까?
- [ ] 코드 정리
- [ ]

**Comment by sonemelody** [comment]
> * [x]  현재 db 구조 괜찮은가? 
⋙ 현재로는 괜찮아보임
> * [x]  태그 추가/삭제를 가능하게 할 것인지 -> tag management 기능을 위한 별도의 fragment/activity 필요 -> 만든다면 drawer에 추가하는 것이 좋겠다. -> 단, 굉장히 귀찮 + 복잡
⋙ 있으면 좋을 것 같기는 한데 일단 보류해두고 다른 작업을 먼저 해야할 듯..
> * [x]  바로 사진 찍어서 업로드 가능하게 하는 기능 살릴 것인지
⋙ 지금은 floating button 중에 +클릭 -> 촬영버튼 / 갤러리선택버튼 이렇게 있는 걸 그냥 +클릭 -> 업로드 이 형식으로 간소화하고 촬영해서 업로드 하는 기능은 그냥 없애도 될 것 같다는 생각..
> * [x]  user image를 넣을까?
⋙ 마이페이지 말하는 거면 있는 게 좋지 않을까?
> * [x]  db를 각 user별로 만들어서 그 안에 각각의 fashion, clothes, statistics 가지도록 만들까?
⋙ 그래야하지 않나...?
> * [x]  rate를 string으로 int로?
⋙ 그냥 count만 할 거면 int로 가도 될 것 가틈
> * [x]  로그인 기능에서 이메일로 인증메일 보내기/이메일 형식이 아니면 warning뜨면서 안 되게 하기 등의 기능 추가
⋙ 이건 없어도 될 것 같은데 나중에 시간 되면 그때 추가해도 되지 않을까?
> * [x]  statistics에서 cloth, temperature를 child로 담지 말고, temperature 구간별로 child만들고 그 안에 cloth로 child만들고 그 안에 count 담는 건?
⋙ temperature 구간별로 child 만드는 게 관리하기 더 편해보여!
